/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kt.sample.app

import kt.sample.Foo;

class App {
    val greeting: String
        get() {
            return "Hello world. from Kotlin"
        }
}

fun doit() {
    for(i in 1..4) {
        println(i)
    }
}

fun main(args: Array<String>) {
    println(App().greeting)

    val f = Foo()
    println(f.message)
    val f1 = Foo("Michael")
    println(f1.message)

    doit()
}
